---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: fondo-gris { }
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "\\#fondo-gris { }"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: ".fondo-gris { }"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "<fondo-gris> { }"
  checked: false
name: 'Cuestionario de selectores: III'
