---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`h3 { }`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`#h3 { }`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`.h3 { }`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`<h3> { }`"
  checked: false
name: 'Cuestionario de selectores: I'
