---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Negro
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Blanco
  checked: true
name: "¡Newton está en todo!"
