---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Serif
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Sans-Serif
  checked: true
name: Familia tipográficas
